media: src/assets
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view: 
      fields: [ title, draft, date ]
    fields:
      - {name: title, label: Title, type: string}
      - {name: draft, label: Is Draft?, type: boolean}
      - {name: date, label: Date, type: date, options: {format: MMM dd yyyy}}
      - {name: summary, label: Summary, type: string, options: {maxlength: 100}}
      - {name: tags, label: Tags, type: string, list: true}
      - name: body
        label: Body
        type: rich-text
        options: 
          path: src/assets
          extensions: [jpg, jpeg, png]