media: public
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    fields:
      - {name: title, label: Title, type: string}
      - {name: date, label: Date, type: date}
      - {name: summary, label: Summary, type: string, options: {maxlength: 100}}
      - {name: body, label: Body, type: rich-text}